name: Benthic GitHub Actions Deployment

on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # ---------------------------------------------
  # REDEPLOY NEW VERSION OF WEBPAGE
  # ---------------------------------------------
    redeploy-frontend:
      runs-on: benthic-hosted
      steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Install and Build
            run: |
              npm ci
              npm run build
            
          - name: Copy Build Files Nginx Directory
            run: |
              # Clear old files
              rm -rv /var/www/benthic-technologies/*
              # Copy new build files
              cp dist/* /var/www/react-app/



