name: Benthic Frontend Redeployment

on: 
  push:
    branches: [main]
    paths:
      - 'benthic-website/**'
  workflow_dispatch:

jobs:
  # ---------------------------------------------
  # REDEPLOY NEW VERSION OF WEBPAGE
  # ---------------------------------------------
    redeploy-frontend:
      runs-on: benthic-hosted

      defaults:
        run:
          working-directory: ./benthic-website

      steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Install and Build
            env:
              NODE_OPTIONS: "--max-old-space-size=5125"
            run: |
              npm ci
              npm run build
            
          - name: Copy Build Files Nginx Directory
            run: |
              # Clear old files
              rm -rf /var/www/benthic-technologies/*
              # Copy new build files
              cp dist/* /var/www/benthic-technologies/



